# Generated by Django 3.2.23 on 2024-07-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FINALApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('contact', models.CharField(max_length=10)),
                ('member_type', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=25)),
            ],
        ),
    ]
