# Generated by Django 3.2.23 on 2024-07-16 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FINALApp', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField()),
                ('event_details', models.TextField()),
                ('event_image', models.ImageField(blank=True, null=True, upload_to='image/')),
            ],
        ),
    ]
