# Generated by Django 3.2.23 on 2024-07-24 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FINALApp', '0006_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='member_type',
        ),
    ]
