# Generated by Django 3.2.23 on 2024-07-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FINALApp', '0007_remove_user_member_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
