# Generated by Django 3.2.23 on 2024-07-25 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FINALApp', '0008_user_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
    ]
