# Generated by Django 3.2.23 on 2024-07-27 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FINALApp', '0010_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
