# Generated by Django 3.2.23 on 2024-07-28 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FINALApp', '0011_alter_user_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Maintenance Issues', 'Maintenance Issues'), ('Safety Concerns', 'Safety Concerns'), ('Noise Complaints', 'Noise Complaints'), ('Cleanliness and Hygiene', 'Cleanliness and Hygiene'), ('Parking and Vehicle Issues', 'Parking and Vehicle Issues'), ('Amenities and Facilities', 'Amenities and Facilities'), ('Billing and Payments', 'Billing and Payments'), ('Community Issues', 'Community Issues'), ('General Complaints', 'General Complaints'), ('Suggestions and Feedback', 'Suggestions and Feedback')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='complaint_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FINALApp.user')),
            ],
        ),
    ]
