# Generated by Django 3.2.23 on 2024-07-28 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FINALApp', '0014_complaint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Complaint',
        ),
    ]
