# Generated by Django 3.2.23 on 2024-07-28 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FINALApp', '0019_maintenancefee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MaintenanceFee',
        ),
    ]
