# Generated by Django 3.2.23 on 2024-08-02 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FINALApp', '0025_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
