# Generated by Django 3.2.23 on 2024-08-02 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FINALApp', '0027_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.DeleteModel(
            name='MaintenanceFee',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
