# Generated by Django 3.2.25 on 2024-08-08 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FINALApp', '0030_chatmessage_chatsession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsession',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='user2',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='ChatSession',
        ),
    ]
