# Generated by Django 3.2.25 on 2024-08-09 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FINALApp', '0035_auto_20240809_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
