# Generated by Django 3.2.25 on 2024-08-09 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FINALApp', '0039_auto_20240809_2116'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
