# Generated by Django 3.2.25 on 2024-08-10 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FINALApp', '0042_auto_20240809_2241'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
