# Generated by Django 3.2.25 on 2024-08-10 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FINALApp', '0046_chatmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
