# Generated by Django 3.2.25 on 2024-08-12 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FINALApp', '0050_auto_20240812_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='bill_image',
            field=models.ImageField(blank=True, null=True, upload_to='bills/'),
        ),
    ]
