# Generated by Django 3.2.25 on 2024-08-12 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FINALApp', '0051_auto_20240812_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='bill_image',
            field=models.ImageField(blank=True, null=True, upload_to='complaints/bills/'),
        ),
    ]
