# Generated by Django 3.2.25 on 2024-08-13 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FINALApp', '0052_alter_complaint_bill_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
