# Generated by Django 3.2.25 on 2024-08-13 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FINALApp', '0054_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='card_cvv',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='card_expiry',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='upi_id',
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FINALApp.user'),
        ),
    ]
