# Generated by Django 3.2.25 on 2024-08-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FINALApp', '0055_auto_20240813_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='upi_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
