# Generated by Django 3.2.25 on 2024-08-13 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FINALApp', '0057_auto_20240813_1535'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={},
        ),
    ]
