# Generated by Django 3.2.25 on 2024-08-16 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FINALApp', '0058_alter_chat_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='datetime',
            new_name='timestamp',
        ),
        migrations.AddField(
            model_name='chat',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
