# Generated by Django 3.2.25 on 2024-08-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FINALApp', '0059_auto_20240816_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='from_user',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='chat',
            name='to_user',
            field=models.CharField(max_length=25),
        ),
    ]
