# Generated by Django 3.2.25 on 2024-08-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FINALApp', '0060_auto_20240816_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_status',
            field=models.CharField(default='Upcoming', max_length=20),
        ),
    ]
