# Generated by Django 3.2.25 on 2024-08-21 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FINALApp', '0061_event_event_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_status',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_link',
        ),
    ]
